enableScripts: false

yarnPath: .yarn/releases/yarn-4.3.0.cjs

nodeLinker: node-modules
nmHoistingLimits: workspaces
npmRegistryServer: "https://registry.yarnpkg.com"
npmAuthToken: "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"
