name: Build and Lint

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-lint:
    name: Build and Lint
    env:
      INFURA_PROJECT_ID: ${{ secrets.INFURA_PROJECT_ID }}
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Set Yarn version to 4.3.0
        run: yarn set version 4.3.0
      - name: Install dependencies
        run: |
          yarn install --immutable || {
            if grep -q '@lavamoat/preinstall-always-fail' /tmp/xfs-*/build.log; then
              echo "Ignoring expected failure of @lavamoat/preinstall-always-fail"
              exit 0
            else
              echo "Unexpected failure during yarn install"
              exit 1
            fi
          }
      - name: Allow scripts
        run: yarn allow-scripts
      - run: yarn lint
      - name: Ensure demo build script works
        run: yarn demo --all
      - name: Validate RC changelog
        if: ${{ startsWith(github.head_ref, 'release/') }}
        run: yarn auto-changelog validate --rc
      - name: Validate changelog
        if: ${{ !startsWith(github.head_ref, 'release/') }}
        run: yarn auto-changelog validate
  all-jobs-pass:
    name: All jobs pass
    runs-on: ubuntu-20.04
    needs:
      - build-lint
    steps:
      - run: echo "Great success!"
