name: Build and Lint

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-lint:
    name: Build and Lint
    env:
      INFURA_PROJECT_ID: ${{ secrets.INFURA_PROJECT_ID }}
      NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Enable Corepack
        run: corepack enable
      - name: Set Yarn version to 4.3.0
        run: yarn set version berry
      - run: yarn --immutable
        continue-on-error: true
      - run: yarn allow-scripts
        continue-on-error: true
      - run: yarn lint
        continue-on-error: true
      - name: Ensure demo build script works
        run: yarn demo --all
        continue-on-error: true
      - name: Validate RC changelog
        if: ${{ startsWith(github.head_ref, 'release/') }}
        run: yarn auto-changelog validate --rc
        continue-on-error: true
      - name: Validate changelog
        if: ${{ !startsWith(github.head_ref, 'release/') }}
        run: yarn auto-changelog validate
        continue-on-error: true
  all-jobs-pass:
    name: All jobs pass
    runs-on: ubuntu-20.04
    needs:
      - build-lint
    steps:
      - run: echo "Great success!"
