name: Publish to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  publish-gh-pages:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Enable Corepack
        run: corepack enable
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - name: Install npm dependencies
        run: yarn --immutable
      - name: Run build script
        run: yarn build:docs
      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@de7ea6f8efb354206b205ef54722213d99067935
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
